### PR TITLE
[NETBEANS-54] Module Review versioning.core

### PR DESCRIPTION
**Pull request by trevlewis**
For issue https://github.com/emilianbold/incubator-netbeans/issues/205

-Add to Apache License. 
-Update nbbuild/build.xml

### CODE REVIEW

**Review by emilianbold — CHANGES_REQUESTED** [review]
@trevlewis , stop introducing whitespace changes. Your patch should have the minimal changes necessary, in this case just the `exclude` line.

**Comment by trevlewis** [comment]
@emilianbold I am not actually doing that. Not sure why that is happening. All I manually did was add the excludes. I will fix that.

**Comment by emilianbold** [comment]
Your text editor is doing that. Use NetBeans.

**Comment by trevlewis** [comment]
@emilianbold My branch got screwed up. I am going to close this PR and open a new one.

**Pull request closed without merging**
