### PR TITLE
[NETBEANS-54] Module Review maven.osgi

### LINKED ISSUE #145: Cleanup NetBeans license header for module maven.osgi
Review and cleanup the license header in maven.osgi

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in maven.osgi:
```
maven.osgi/src/org/netbeans/modules/maven/osgi/templates/Activator.java.template

```

### PR DESCRIPTION
**Pull request by mclay**
Fixes #145

### CODE REVIEW

**Comment by mclay** [comment]
mixed up branches here is the correct pull request for this one https://github.com/emilianbold/incubator-netbeans/issues/145

**Review by emilianbold — CHANGES_REQUESTED** [review]
The template file is user-visible so it must be included from the "rat" task in nbbuild/build.xml

**Comment by emilianbold** [comment]
@mclay still interested in finishing this one?

**Comment by mclay** [comment]
@emilianbold yes i will finish within the next 1-2 days

**Comment by mclay** [comment]
done - please review it again

**Review by emilianbold — CHANGES_REQUESTED** [review]
Since we are excluding Activator.java.template there's no need to add a license there.

Please revert your changes from Activator.java.template and just leave the build.xml exclusion.

**Comment by emilianbold** [comment]
Hacktoberfest is over. Closing this PR. Feel free to reopen one for the issue, I will merge it if it's ok.

**Pull request closed without merging**
