### PR TITLE
[NETBEANS-54] Module Review maven.htmlui 

### LINKED ISSUE #142: Cleanup NetBeans license header for module maven.htmlui
Review and cleanup the license header in maven.htmlui

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in maven.htmlui:
```
maven.htmlui/src/org/netbeans/modules/maven/htmlui/Bundle.properties
maven.htmlui/src/org/netbeans/modules/maven/htmlui/UIDefaults
maven.htmlui/src/org/netbeans/modules/maven/htmlui/description.html
maven.htmlui/src/org/netbeans/modules/maven/htmlui/wizard-gtk.css
maven.htmlui/src/org/netbeans/modules/maven/htmlui/wizard-mac.css
maven.htmlui/src/org/netbeans/modules/maven/htmlui/wizard-metal.css
maven.htmlui/src/org/netbeans/modules/maven/htmlui/wizard-nimbus.css
maven.htmlui/src/org/netbeans/modules/maven/htmlui/wizard-win.css

```

### PR DESCRIPTION
**Pull request by gezapeti**
Fixes #142. Added headers to non-empty css, html and properties file. There is a tricky file, maven.htmlui/src/org/netbeans/modules/maven/htmlui/UIDefaults 
I don't think I can add a license header into that without breaking things. Please let me know if there is a way to do so or how I can add it to an ignore list.

### CODE REVIEW

**Comment by emilianbold** [comment]
The ignore list would be the Rat excludes from nbbuild/build.xml

**Comment by gezapeti** [comment]
Added the file to the ignore list.

**Review by emilianbold — CHANGES_REQUESTED** [review]
I still see random whitespace changes...

**Comment by junichi11** [comment]
I've sorted rat excludes. (This PR already had the conflicting file(nbbuild/build.xml))

**Comment by emilianbold** [comment]
@junichi11 thanks! It's a single line, shouldn't be hard to merge.

**Comment by gezapeti** [comment]
Rebased & removed whitespaces

**Review by emilianbold — APPROVED** [review]

**Pull request merged**
