### PR TITLE
[NETBEANS-54] Module Review Apache License testng.maven

### LINKED ISSUE #200: Cleanup NetBeans license header for module testng.maven
Review and cleanup the license header in testng.maven

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in testng.maven:
```
testng.maven/src/org/netbeans/modules/testng/maven/Bundle.properties

```

### PR DESCRIPTION
**Pull request by trevlewis**
Fix #200

Update old Oracle license to Apache License.

### CODE REVIEW

**Comment by trevlewis** [comment]
@emilianbold do you want the title of the PRs to be:
1)[NETBEANS-54] Module Review
2)[NETBEANS-54] Module Review testng.maven
3)[NETBEANS-54] Module Review Apache License testng.maven

I will change the rest of them to what you want.

**Comment by emilianbold** [comment]
They should be

[NETBEANS-54] Module Review testng.maven

Read https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review for the long explanations.

**Comment by emilianbold** [comment]
BTW, could you configure your git user.name and user.email? 
You show up as Trevor trevlewis@users.noreply.github.com. Some proper name + real email would look much better.

**Comment by trevlewis** [comment]
Hmm that is weird because I have it setup locally.

C:\dev\gitspace\incubator-netbeans (181.refactoring.java)
λ git config user.name
trevlewis

C:\dev\gitspace\incubator-netbeans (181.refactoring.java)
λ git config user.email
tdlewis7@gmail.com

**Comment by emilianbold** [comment]
Nope, look at your previous commit: https://github.com/apache/incubator-netbeans/commit/1cb625d13eaeff0566347fa0527e261b19704e58.patch

From: Trevor <trevlewis@users.noreply.github.com>

Also look at your own git log.

**Comment by trevlewis** [comment]
Okay got it now. I had it set to not use my email in my GitHub profile.

**Pull request merged**
