### PR TITLE
[NETBEANS-54] Module Review websvc.saas.api

### LINKED ISSUE #210: Cleanup NetBeans license header for module websvc.saas.api
Review and cleanup the license header in websvc.saas.api

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in websvc.saas.api:
```
websvc.saas.api/src/org/netbeans/modules/websvc/saas/oauth/OAuthAuthorizationPanelNb.template
websvc.saas.api/src/org/netbeans/modules/websvc/saas/oauth/OAuthSearchJSON.template
websvc.saas.api/src/org/netbeans/modules/websvc/saas/oauth/OAuthSearchXML.template
websvc.saas.api/src/org/netbeans/modules/websvc/saas/spi/Bundle.properties
websvc.saas.api/test/unit/src/org/netbeans/modules/websvc/saas/model/application.wadl
websvc.saas.api/test/unit/src/org/netbeans/modules/websvc/saas/util/rootGroup.xml

```

### PR DESCRIPTION
**Pull request by trevlewis**
Fix #210

Update old Oracle license to Apache License.

### CODE REVIEW

**Comment by emilianbold** [comment]
What about the other files, like websvc.saas.api/src/org/netbeans/modules/websvc/saas/model/wadl200902.xsd ?

**Comment by trevlewis** [comment]
These 2 files don't exist. I searched for them and they are not in the project. websvc.saas.api/src/org/netbeans/modules/websvc/saas/model/wadl20061109.xsd
websvc.saas.api/src/org/netbeans/modules/websvc/saas/model/wadl200902.xsd

Do you want the license header added to all files, even if there isn't one present?

**Comment by emilianbold** [comment]
I still see them:

```
$ ls websvc.saas.api/src/org/netbeans/modules/websvc/saas/model/*.xsd
websvc.saas.api/src/org/netbeans/modules/websvc/saas/model/SaasServices.xsd
websvc.saas.api/src/org/netbeans/modules/websvc/saas/model/oauth-metadata.xsd
websvc.saas.api/src/org/netbeans/modules/websvc/saas/model/wadl20061109.xsd
websvc.saas.api/src/org/netbeans/modules/websvc/saas/model/wadl200902.xsd
```

> Do you want the license header added to all files, even if there isn't one present?

If it makes sense, yes.

**Review by emilianbold — CHANGES_REQUESTED** [review]
What about the other files? `websvc.saas.api/src/org/netbeans/modules/websvc/saas/model/wadl20061109.xsd` clearly has the old Oracle copyright.

**Comment by trevlewis** [comment]
image

@emilianbold These 2 files aren't even in your master branch, so not sure why you have them in your local.
websvc.saas.api/src/org/netbeans/modules/websvc/saas/model/wadl20061109.xsd
websvc.saas.api/src/org/netbeans/modules/websvc/saas/model/wadl200902.xsd

and the other 2 already have the license updated.
websvc.saas.api/src/org/netbeans/modules/websvc/saas/model/SaasServices.xsd
websvc.saas.api/src/org/netbeans/modules/websvc/saas/model/oauth-metadata.xsd

**Comment by emilianbold** [comment]
Ah, interesting, they are part of external/websvc-saas-api-external-resources.zip

**Comment by trevlewis** [comment]
So, is there anything I need to do more for this PR or is it good to go?

**Comment by emilianbold** [comment]
Thanks for noticing those two files, it triggered a separate discussion on the mailing list.

I would like to visit all of the files:

> websvc.saas.api/src/org/netbeans/modules/websvc/saas/oauth/OAuthAuthorizationPanelNb.template
> websvc.saas.api/src/org/netbeans/modules/websvc/saas/oauth/OAuthSearchJSON.template
> websvc.saas.api/src/org/netbeans/modules/websvc/saas/oauth/OAuthSearchXML.template
> 

Exclude in build.xml?

> websvc.saas.api/src/org/netbeans/modules/websvc/saas/spi/Bundle.properties

Included in the PR.

> websvc.saas.api/test/unit/src/org/netbeans/modules/websvc/saas/model/application.wadl
> websvc.saas.api/test/unit/src/org/netbeans/modules/websvc/saas/util/rootGroup.xml

Exclude also?

**Review by emilianbold — APPROVED** [review]

**Comment by trevlewis** [comment]
Exclude in build.xml?
websvc.saas.api/src/org/netbeans/modules/websvc/saas/spi/Bundle.properties

@emilianbold So should I revert the changes for this file and then exclude it?

**Comment by trevlewis** [comment]
Never-mind I see the wording. I will check the other files and exclude them if need be.

**Comment by trevlewis** [comment]
So I am going to add the template files, application.wadl file, and rootGroup.xml to be excluded.

**Pull request merged**
