### PR TITLE
[NETBEANS-54] Module Review Apache License javafx2.project

### LINKED ISSUE #111: Cleanup NetBeans license header for module javafx2.project
Review and cleanup the license header in javafx2.project

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in javafx2.project:
```
javafx2.project/src/org/netbeans/modules/javafx2/project/templates/CSS_empty.template
javafx2.project/src/org/netbeans/modules/javafx2/project/templates/FXML_controller.template
javafx2.project/src/org/netbeans/modules/javafx2/project/templates/FXML_fxml.template
javafx2.project/src/org/netbeans/modules/javafx2/project/templates/FXML_java_1.template
javafx2.project/src/org/netbeans/modules/javafx2/project/templates/FXML_java_2.template
javafx2.project/src/org/netbeans/modules/javafx2/project/templates/FXMain.template
javafx2.project/src/org/netbeans/modules/javafx2/project/templates/FXPreloader.template
javafx2.project/src/org/netbeans/modules/javafx2/project/templates/FXSwingMain.template
javafx2.project/src/org/netbeans/modules/javafx2/project/templates/FXSwingTemplate.html_
javafx2.project/src/org/netbeans/modules/javafx2/project/templates/FXSwingTemplateApplet.jnlp_
javafx2.project/src/org/netbeans/modules/javafx2/project/templates/FXSwingTemplateApplication.jnlp_
javafx2.project/src/org/netbeans/modules/javafx2/project/templates/NewProjectFXML.template
javafx2.project/src/org/netbeans/modules/javafx2/project/templates/jfx-impl.xml_

```

### PR DESCRIPTION
**Pull request by ghost**
Fixes #111

Due to note:

in the file javafx2.project/src/org/netbeans/modules/javafx2/project/templates/jfx-impl.xml_
So I just leave it without any change

### CODE REVIEW

**Comment by junichi11** [comment]
Could you add the following files to rat excludes[1] after you undo the license headers. These files are used as templates when a user creates a new project.
- FXSwingTemplate.html_
- FXSwingTemplateApplet.jnlp_
- FXSwingTemplateApplication.jnlp_

apache-netbeans-module-review-javafx2 project


Then, *.template files should be also added there after you undo the license headers.
I don't know if project templates are visible for users.

see: https://github.com/emilianbold/incubator-netbeans/pull/282/files#diff-fa67ba03971f6d21c0ff2493bf5d922f

[1] https://github.com/bjansen/incubator-netbeans/blob/65de90b70575ba37044b533bf4e98a89851cdc8e/nbbuild/build.xml#L1949-L1974

**Comment by emilianbold** [comment]
Looks to me all that need to be done here is an exclude rule for javafx2.project/src/org/netbeans/modules/javafx2/project/templates/*

**Review by emilianbold — CHANGES_REQUESTED** [review]
Just exclude javafx2.project/src/org/netbeans/modules/javafx2/project/templates/*

**Comment by ghost** [comment]
Done

**Review by emilianbold — APPROVED** [review]

**Comment by emilianbold** [comment]
@trantuyen1505: not sure if it was intentional but it was sneaky to add your change in the middle in order to make sure you don't get conflicts if somebody else appends an exception 👍

**Pull request merged**
