### PR TITLE
[NETBEANS-54] Module Review versioning.core 

### PR DESCRIPTION
**Pull request by trevlewis**
For issue https://github.com/emilianbold/incubator-netbeans/issues/205

-Add to Apache License. 
-Update nbbuild/build.xml

### CODE REVIEW

**Comment by trevlewis** [comment]
@emilianbold I got all the whitespace issues taken care of and I got Netbeans set up.

**Review by emilianbold — CHANGES_REQUESTED** [review]
I don't understand, why are you excluding diff/ stuff when this PR is about versioning.core?

You are very distracted.

**Comment by trevlewis** [comment]
@emilianbold Yes, I apologize for that. I was trying to get Netbeans set up and look at other PR's as well. I am all set up now so I should have no more simple mistakes like this. Thank you for your patience. 

I am getting the excludes fixed right now.

**Comment by emilianbold** [comment]
Have you heard of Giotto’s perfect circle?

You aim should be to create a perfect commit and PR.

**Review by emilianbold — APPROVED** [review]

**Comment by emilianbold** [comment]
Sigh... in this block:

> +# 
> +#  http://www.apache.org/licenses/LICENSE-2.0
> +# 

you have an extra space after '#' for the 'empty' comment lines.

**Comment by trevlewis** [comment]
That was copied for another file that was committed already, so not sure why mine needs to be different then what is already in the code, but I fixed the whitespaces after the empty comments.

**Comment by emilianbold** [comment]
> $ grep -R -1 '^#.*http://www.apache.org/licenses/LICENSE-2.0' . | grep -v "http://www.apache.org/licenses/LICENSE-2.0" | grep -v '^\-\-$' | grep -v '#$' | grep -v '^Binary file'

> ./spi.java.hints/src/org/netbeans/spi/java/hints/Bundle.properties-# 

> $ git log ./spi.java.hints/src/org/netbeans/spi/java/hints/Bundle.properties
> commit cc42f40263c42b1e5fc6dabb1b934229cf26ace5
> Author: Trevor <trevlewis@users.noreply.github.com>
> Date:   Fri Oct 6 08:06:01 2017 -0600
> 
>     [NETBEANS-54] Module Review spi.java.hints

**Pull request merged**
