### PR TITLE
[NETBEANS-54] Module Review javahelp

### LINKED ISSUE #113: Cleanup NetBeans license header for module javahelp
Review and cleanup the license header in javahelp

Oracle donated NetBeans to the Apache Software Foundation.

Your task now is to *replace* the old license header that has Oracle (and/or Sun Microsystems
and/or NetBeans) in it with the standard Apache Software Foundation license header.

For an empty file that supports headers you must *add* the Apache license header.

Note that you have to use the proper license header for Java, .properties or HTML files.
Look at the nearby files for templates and copy-paste the license header.

When done commit the changes with a commit message that starts with first line
"[NETBEANS-54] Module Review <module>" and a message body describing your review.

See a longer explanation about what we are doing here: https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review

Please announce in a comment when you have started work.

Files that need to be looked at in javahelp:
```
javahelp/src/org/netbeans/modules/javahelp/resources/favorites_2_0.dtd
javahelp/src/org/netbeans/modules/javahelp/resources/helpset_1_0.dtd
javahelp/src/org/netbeans/modules/javahelp/resources/helpset_2_0.dtd
javahelp/src/org/netbeans/modules/javahelp/resources/index_1_0.dtd
javahelp/src/org/netbeans/modules/javahelp/resources/index_2_0.dtd
javahelp/src/org/netbeans/modules/javahelp/resources/map_1_0.dtd
javahelp/src/org/netbeans/modules/javahelp/resources/map_2_0.dtd
javahelp/src/org/netbeans/modules/javahelp/resources/toc_1_0.dtd
javahelp/src/org/netbeans/modules/javahelp/resources/toc_2_0.dtd

```

### PR DESCRIPTION
**Pull request by varaghar**
Fix #113

### CODE REVIEW

**Comment by emilianbold** [comment]
Hm, these have a Copyright (c) 2001 Sun Microsystems... Let's postpone until cleared on the dev@ mailing list.

**Review by emilianbold — CHANGES_REQUESTED** [review]
Awaiting approval.

**Comment by geertjanw** [comment]
Anything copyrighted to Sun Microsystems belonged to Oracle prior to Oracle's donation to Apache and hence can be relicensed to Apache now.

**Comment by emilianbold** [comment]
@varaghar please re-do the PR against apache/incubator-netbeans. The old header is non-standard so I would prefer an Oracle employee to push it.

**Comment by geertjanw** [comment]
If the license is an Oracle license or a Sun license, regardless of whether it is non-standard or not, the file has been donated by Oracle to Apache and anyone can relicense it.

**Comment by emilianbold** [comment]
I understood but I'm not pushing that.

**Comment by geertjanw** [comment]
It's no different to anything else, but, whatever.

**Comment by emilianbold** [comment]
My 'mandate' is based on Oracle's donation to Apache.

Basically, since I don't see Oracle's name there I'd rather have someone from Oracle change it. 

Although, of course, I know Oracle bought Sun Microsystems, etc.

**Pull request closed without merging**
